[2025-03-11 07:57:13,026] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-11 07:57:13,076] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET / 200 [0.17, 127.0.0.1:57523]
[2025-03-11 07:57:13,456] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:57527]
[2025-03-11 07:57:13,514] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57527]
[2025-03-11 07:57:13,792] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/PermInfo/'>
[2025-03-11 07:57:13,802] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /PermInfo/ 200 [0.02, 127.0.0.1:57523]
[2025-03-11 07:57:13,851] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 07:57:13,877] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:57523]
[2025-03-11 07:57:26,102] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:26: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/SpecDownload/ManagementSop-summary/'>
[2025-03-11 07:57:26,123] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:57523]
[2025-03-11 07:57:26,181] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:57568]
[2025-03-11 07:57:26,185] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57568]
[2025-03-11 07:57:26,407] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:26: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/ManagementSop-summary/'>
[2025-03-11 07:57:26,428] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.13, 127.0.0.1:57523]
[2025-03-11 07:57:26,473] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 07:57:26: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 07:57:26,508] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.17, 127.0.0.1:57524]
[2025-03-11 07:57:28,486] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57527]
[2025-03-11 08:56:41,644] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:56:41: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/SpecDownload/ManagementSop-summary/'>
[2025-03-11 08:56:41,666] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.13, 127.0.0.1:59603]
[2025-03-11 08:56:41,676] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57568]
[2025-03-11 08:56:41,775] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59607]
[2025-03-11 08:56:41,780] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59607]
[2025-03-11 08:56:42,049] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:56:42: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/ManagementSop-summary/'>
[2025-03-11 08:56:42,063] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:59603]
[2025-03-11 08:56:42,085] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:56:42: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 08:56:42,111] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:59604]
[2025-03-11 08:57:09,037] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:09: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-11 08:57:09,069] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.08, 127.0.0.1:59604]
[2025-03-11 08:57:09,086] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59607]
[2025-03-11 08:57:09,191] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59668]
[2025-03-11 08:57:09,196] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59668]
[2025-03-11 08:57:09,398] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:09: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-11 08:57:09,414] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.05, 127.0.0.1:59604]
[2025-03-11 08:57:09,436] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:09: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 08:57:09,472] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:59603]
[2025-03-11 08:57:15,542] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 08:57:15,558] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.05, 127.0.0.1:59603]
[2025-03-11 08:57:15,565] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59668]
[2025-03-11 08:57:15,607] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59681]
[2025-03-11 08:57:15,612] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59681]
[2025-03-11 08:57:15,874] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/SpecDownload-summary/'>
[2025-03-11 08:57:15,886] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/SpecDownload-summary/ 200 [0.20, 127.0.0.1:59603]
[2025-03-11 08:57:15,923] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:57:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 08:57:15,960] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.25, 127.0.0.1:59604]
[2025-03-11 08:58:07,538] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59604]
[2025-03-11 08:58:07,545] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:59603]
[2025-03-11 08:58:07,550] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:59798]
[2025-03-11 08:58:07,616] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:59798]
[2025-03-11 08:58:12,344] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:58:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 08:58:12,359] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:59798]
[2025-03-11 08:58:12,366] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59681]
[2025-03-11 08:58:12,434] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:59798]
[2025-03-11 08:58:12,445] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59798]
[2025-03-11 08:58:12,469] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59806]
[2025-03-11 08:58:12,471] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59806]
[2025-03-11 08:58:12,522] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:59798]
[2025-03-11 08:58:12,528] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:59603]
[2025-03-11 08:58:12,598] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:58:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 08:58:12,611] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:59603]
[2025-03-11 08:58:12,623] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 08:58:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 08:58:12,649] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:59798]
[2025-03-11 09:02:03,052] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:02:03,064] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:60370]
[2025-03-11 09:02:03,149] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:60370]
[2025-03-11 09:02:03,163] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:60370]
[2025-03-11 09:02:03,201] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60373]
[2025-03-11 09:02:03,311] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:60370]
[2025-03-11 09:02:03,320] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:60371]
[2025-03-11 09:02:03,321] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60373]
[2025-03-11 09:02:03,399] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:02:03,409] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:60371]
[2025-03-11 09:02:03,423] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:02:03,443] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:60370]
[2025-03-11 09:02:23,953] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:02:23,967] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:60370]
[2025-03-11 09:02:24,825] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:24: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:02:24,839] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:60370]
[2025-03-11 09:02:52,694] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:02:52: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:02:52,702] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:60370]
[2025-03-11 09:04:55,444] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:04:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:04:55,456] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:60695]
[2025-03-11 09:04:55,532] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:60695]
[2025-03-11 09:04:55,555] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:60695]
[2025-03-11 09:04:55,597] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60699]
[2025-03-11 09:04:55,654] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60699]
[2025-03-11 09:04:55,680] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:60695]
[2025-03-11 09:04:55,685] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:60693]
[2025-03-11 09:04:55,798] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:04:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:04:55,815] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:60693]
[2025-03-11 09:04:55,826] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:04:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:04:55,846] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:60695]
[2025-03-11 09:05:03,022] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:05:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:05:03,053] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:60695]
[2025-03-11 09:10:56,037] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:10:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:10:56,060] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.20, 127.0.0.1:61377]
[2025-03-11 09:10:56,153] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61377]
[2025-03-11 09:10:56,161] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61379]
[2025-03-11 09:10:56,176] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61381]
[2025-03-11 09:10:56,320] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:61377]
[2025-03-11 09:10:56,330] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.02, 127.0.0.1:61379]
[2025-03-11 09:10:56,338] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61381]
[2025-03-11 09:10:56,343] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:10:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:10:56,358] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.05, 127.0.0.1:61382]
[2025-03-11 09:10:56,403] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:10:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:10:56,433] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:61383]
[2025-03-11 09:33:55,411] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:33:55,429] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:63850]
[2025-03-11 09:33:55,558] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:33:55,583] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:33:55,658] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63856]
[2025-03-11 09:33:55,775] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:33:55,780] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63856]
[2025-03-11 09:33:55,786] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:33:56,653] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 117, in SubscriptionStatus_view
    for i in Budget.objects.filter(Year=YearSearch, Ledger=LedgerSearch).first():
TypeError: 'Budget' object is not iterable
[2025-03-11 09:33:56,662] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:33:56,666] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.68, 127.0.0.1:63849]
[2025-03-11 09:33:56,707] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:33:56,750] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.68, 127.0.0.1:63850]
[2025-03-11 09:33:58,498] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:58: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:33:58,513] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:63850]
[2025-03-11 09:33:58,521] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63856]
[2025-03-11 09:33:58,594] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:33:58,603] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:33:58,646] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63866]
[2025-03-11 09:33:58,651] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63866]
[2025-03-11 09:33:58,723] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:33:58,733] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:63850]
[2025-03-11 09:33:58,893] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 117, in SubscriptionStatus_view
    for i in Budget.objects.filter(Year=YearSearch, Ledger=LedgerSearch).first():
TypeError: 'Budget' object is not iterable
[2025-03-11 09:33:58,898] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:58: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:33:58,904] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.09, 127.0.0.1:63850]
[2025-03-11 09:33:58,927] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:33:58: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:33:58,962] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:63849]
[2025-03-11 09:34:00,786] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:00: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/KnowIssue/KnowIssue-search/'>
[2025-03-11 09:34:00,802] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /KnowIssue/KnowIssue-search/ 200 [0.08, 127.0.0.1:63849]
[2025-03-11 09:34:00,811] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63866]
[2025-03-11 09:34:00,894] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:34:00,904] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:34:00,910] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63875]
[2025-03-11 09:34:00,913] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63875]
[2025-03-11 09:34:00,951] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:34:00,960] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:63849]
[2025-03-11 09:34:01,027] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:01: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/KnowIssue/KnowIssue-search/'>
[2025-03-11 09:34:01,038] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /KnowIssue/KnowIssue-search/ 200 [0.04, 127.0.0.1:63849]
[2025-03-11 09:34:01,055] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:01: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:34:01,086] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:63850]
[2025-03-11 09:34:03,667] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:34:03,694] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:63850]
[2025-03-11 09:34:03,706] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63875]
[2025-03-11 09:34:03,800] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63850]
[2025-03-11 09:34:03,809] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:34:03,818] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63886]
[2025-03-11 09:34:03,821] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63886]
[2025-03-11 09:34:03,856] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63849]
[2025-03-11 09:34:03,865] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:63850]
[2025-03-11 09:34:04,007] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 117, in SubscriptionStatus_view
    for i in Budget.objects.filter(Year=YearSearch, Ledger=LedgerSearch).first():
TypeError: 'Budget' object is not iterable
[2025-03-11 09:34:04,011] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:34:04,016] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.11, 127.0.0.1:63850]
[2025-03-11 09:34:04,064] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:34:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:34:04,112] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.19, 127.0.0.1:63849]
[2025-03-11 09:35:28,949] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:35:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:35:28,962] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:64059]
[2025-03-11 09:35:29,030] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64059]
[2025-03-11 09:35:29,039] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:64059]
[2025-03-11 09:35:29,053] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64062]
[2025-03-11 09:35:29,103] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64060]
[2025-03-11 09:35:29,108] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64059]
[2025-03-11 09:35:29,110] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64062]
[2025-03-11 09:35:29,401] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 122, in SubscriptionStatus_view
    "Dec": i.Dec}
TypeError: unhashable type: 'dict'
[2025-03-11 09:35:29,404] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:35:29: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:35:29,406] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.25, 127.0.0.1:64059]
[2025-03-11 09:35:29,414] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:35:29: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:35:29,448] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.29, 127.0.0.1:64060]
[2025-03-11 09:36:19,886] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:36:19: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:36:19,900] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:64152]
[2025-03-11 09:36:19,969] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64152]
[2025-03-11 09:36:19,978] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:64152]
[2025-03-11 09:36:19,996] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64155]
[2025-03-11 09:36:20,058] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64153]
[2025-03-11 09:36:20,066] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64152]
[2025-03-11 09:36:20,069] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64155]
[2025-03-11 09:36:20,382] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 123, in SubscriptionStatus_view
    "Dec": i.Dec}
TypeError: unhashable type: 'dict'
[2025-03-11 09:36:20,384] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:36:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:36:20,385] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.27, 127.0.0.1:64152]
[2025-03-11 09:36:20,416] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:36:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:36:20,440] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.32, 127.0.0.1:64153]
[2025-03-11 09:37:52,302] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:37:52: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:37:52,321] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.08, 127.0.0.1:64346]
[2025-03-11 09:37:52,400] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:64346]
[2025-03-11 09:37:52,407] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64347]
[2025-03-11 09:37:52,422] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64350]
[2025-03-11 09:37:52,477] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64346]
[2025-03-11 09:37:52,482] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64347]
[2025-03-11 09:37:52,484] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64350]
[2025-03-11 09:37:52,557] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:37:52: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:37:52,569] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:64347]
[2025-03-11 09:37:52,597] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:37:52: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:37:52,630] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:64346]
[2025-03-11 09:42:59,579] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:42:59: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:42:59,590] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:64867]
[2025-03-11 09:42:59,678] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64867]
[2025-03-11 09:42:59,700] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:64867]
[2025-03-11 09:42:59,735] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64873]
[2025-03-11 09:42:59,796] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64873]
[2025-03-11 09:42:59,816] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64867]
[2025-03-11 09:42:59,857] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64867]
[2025-03-11 09:42:59,962] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:42:59: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:42:59,975] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:64867]
[2025-03-11 09:43:00,000] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:43:00: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:43:00,034] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:64866]
[2025-03-11 09:44:11,928] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:44:11: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:44:11,949] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.18, 127.0.0.1:64985]
[2025-03-11 09:44:12,048] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64985]
[2025-03-11 09:44:12,068] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:64985]
[2025-03-11 09:44:12,117] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64988]
[2025-03-11 09:44:12,263] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64985]
[2025-03-11 09:44:12,271] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:64986]
[2025-03-11 09:44:12,274] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64988]
[2025-03-11 09:44:12,317] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:44:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:44:12,328] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.02, 127.0.0.1:64986]
[2025-03-11 09:44:12,347] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:44:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:44:12,372] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:64985]
[2025-03-11 09:44:21,372] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 331, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:44:21,387] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:44:21: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:44:21,390] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [0.93, 127.0.0.1:64985]
[2025-03-11 09:46:13,928] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 332, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:46:13,933] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:46:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:46:13,939] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [0.25, 127.0.0.1:65232]
[2025-03-11 09:47:16,189] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 332, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:47:16,195] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:47:16: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:47:16,203] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [0.31, 127.0.0.1:65349]
[2025-03-11 09:47:49,958] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 332, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:47:49,961] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:47:49: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:47:49,962] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [0.06, 127.0.0.1:65349]
[2025-03-11 09:48:03,934] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:48:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-11 09:48:03,963] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET / 200 [0.12, 127.0.0.1:65451]
[2025-03-11 09:48:04,193] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:65454]
[2025-03-11 09:48:04,245] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65454]
[2025-03-11 09:48:04,430] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:48:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/PermInfo/'>
[2025-03-11 09:48:04,443] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /PermInfo/ 200 [0.03, 127.0.0.1:65451]
[2025-03-11 09:48:04,505] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:48:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:48:04,533] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:65451]
[2025-03-11 09:48:07,457] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65454]
[2025-03-11 09:48:10,688] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 332, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:48:10,707] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:48:10: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:48:10,711] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [1.08, 127.0.0.1:65451]
[2025-03-11 09:49:28,588] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/ReceiptAmount/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 332, in ReceiptAmount_view
    ReceiptAmount.objects.filter(id=ID).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 693, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1349, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 
[2025-03-11 09:49:28,596] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:49:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:49:28,607] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 500 [0.48, 127.0.0.1:49263]
[2025-03-11 09:52:36,418] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:52:36: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-11 09:52:36,435] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.08, 127.0.0.1:50139]
[2025-03-11 09:52:46,554] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:52:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:52:46,567] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:50139]
[2025-03-11 09:52:46,665] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:50139]
[2025-03-11 09:52:46,699] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:50139]
[2025-03-11 09:52:46,732] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50152]
[2025-03-11 09:52:46,868] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:50139]
[2025-03-11 09:52:46,878] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:50146]
[2025-03-11 09:52:46,881] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50152]
[2025-03-11 09:52:48,003] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 132, in SubscriptionStatus_view
    "Total": i.Jan + i.Feb + i.Mar + i.Apr + i.May + i.Jun + i.Jul + i.Aug + i.Sep + i.Oct + i.Nov + i.Dec
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
[2025-03-11 09:52:48,013] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:52:48: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:52:48,017] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [1.12, 127.0.0.1:50146]
[2025-03-11 09:52:48,054] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:52:48: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:52:48,099] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.19, 127.0.0.1:50139]
[2025-03-11 09:58:54,419] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:58:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:58:54,432] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:50768]
[2025-03-11 09:58:54,519] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:50768]
[2025-03-11 09:58:54,531] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:50768]
[2025-03-11 09:58:54,578] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:50771]
[2025-03-11 09:58:54,640] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:50771]
[2025-03-11 09:58:54,659] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:50768]
[2025-03-11 09:58:54,663] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:50769]
[2025-03-11 09:58:54,773] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:58:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 09:58:54,784] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:50769]
[2025-03-11 09:58:54,813] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 09:58:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 09:58:54,839] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:50768]
[2025-03-11 10:06:50,263] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:06:50: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:06:50,276] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:51727]
[2025-03-11 10:06:50,399] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51727]
[2025-03-11 10:06:50,417] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51727]
[2025-03-11 10:06:50,485] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51733]
[2025-03-11 10:06:50,596] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51733]
[2025-03-11 10:06:50,606] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51727]
[2025-03-11 10:06:50,662] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51727]
[2025-03-11 10:06:51,307] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 132, in SubscriptionStatus_view
    "Total": i.Jan + i.Feb + i.Mar + i.Apr + i.May + i.Jun + i.Jul + i.Aug + i.Sep + i.Oct + i.Nov + i.Dec
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
[2025-03-11 10:06:51,312] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:06:51: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:06:51,315] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.49, 127.0.0.1:51727]
[2025-03-11 10:06:51,351] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:06:51: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:06:51,381] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.55, 127.0.0.1:51725]
[2025-03-11 10:07:14,743] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:14: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:07:14,775] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:51784]
[2025-03-11 10:07:14,879] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51784]
[2025-03-11 10:07:14,887] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51785]
[2025-03-11 10:07:14,956] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51788]
[2025-03-11 10:07:15,048] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51788]
[2025-03-11 10:07:15,081] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51785]
[2025-03-11 10:07:15,097] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51785]
[2025-03-11 10:07:15,275] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:07:15,293] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:51785]
[2025-03-11 10:07:15,333] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:07:15,366] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:51784]
[2025-03-11 10:07:47,246] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:47: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:07:47,265] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.19, 127.0.0.1:51963]
[2025-03-11 10:07:47,351] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51963]
[2025-03-11 10:07:47,360] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:51964]
[2025-03-11 10:07:47,374] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51967]
[2025-03-11 10:07:47,525] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:51963]
[2025-03-11 10:07:47,537] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.03, 127.0.0.1:51964]
[2025-03-11 10:07:47,541] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51967]
[2025-03-11 10:07:47,563] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:47: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:07:47,582] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:51968]
[2025-03-11 10:07:47,620] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:07:47: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:07:47,655] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.14, 127.0.0.1:51969]
[2025-03-11 10:10:19,964] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:19: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:10:19,978] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.08, 127.0.0.1:52237]
[2025-03-11 10:10:20,043] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52237]
[2025-03-11 10:10:20,056] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:52237]
[2025-03-11 10:10:20,075] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52240]
[2025-03-11 10:10:20,150] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:52237]
[2025-03-11 10:10:20,156] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52238]
[2025-03-11 10:10:20,158] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52240]
[2025-03-11 10:10:20,473] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 151, in SubscriptionStatus_view
    mock_data[1]["Total"] = Total_Budget
IndexError: list index out of range
[2025-03-11 10:10:20,476] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:10:20,478] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.29, 127.0.0.1:52238]
[2025-03-11 10:10:20,496] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:10:20,529] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.33, 127.0.0.1:52237]
[2025-03-11 10:10:45,154] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:45: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:10:45,184] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.08, 127.0.0.1:52299]
[2025-03-11 10:10:45,258] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52299]
[2025-03-11 10:10:45,269] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52299]
[2025-03-11 10:10:45,275] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52304]
[2025-03-11 10:10:45,324] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:52299]
[2025-03-11 10:10:45,330] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52301]
[2025-03-11 10:10:45,331] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52304]
[2025-03-11 10:10:45,390] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:45: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:10:45,404] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:52301]
[2025-03-11 10:10:45,437] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:10:45: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:10:45,478] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:52299]
[2025-03-11 10:41:03,812] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:41:03,823] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:56441]
[2025-03-11 10:41:03,933] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:56441]
[2025-03-11 10:41:03,949] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:56441]
[2025-03-11 10:41:04,004] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:56445]
[2025-03-11 10:41:04,081] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:56445]
[2025-03-11 10:41:04,126] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:56441]
[2025-03-11 10:41:04,166] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:56441]
[2025-03-11 10:41:04,885] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 194, in SubscriptionStatus_view
    print(monthly_totals)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 244, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 268, in __iter__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1017, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 449, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 50, in pre_sql_setup
    self.setup_query()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 41, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 244, in get_select
    sql, params = self.compile(col, select_format=True)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 388, in compile
    sql, params = vendor_impl(self, self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 162, in as_mysql
    if self.output_field.get_internal_type() == 'DurationField':
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 256, in output_field
    output_field = self._resolve_output_field()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 288, in _resolve_output_field
    sources_iter = (source for source in self.get_source_fields() if source is not None)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 25, in get_source_fields
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 25, in <listcomp>
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 269, in _output_field_or_none
    return self.output_field
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 256, in output_field
    output_field = self._resolve_output_field()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 291, in _resolve_output_field
    raise FieldError('Expression contains mixed types. You must set output_field.')
django.core.exceptions.FieldError: Expression contains mixed types. You must set output_field.
[2025-03-11 10:41:04,911] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:41:04,914] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.57, 127.0.0.1:56441]
[2025-03-11 10:41:04,952] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:41:04,978] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.62, 127.0.0.1:56442]
[2025-03-11 10:41:49,790] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:49: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:41:49,805] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:56517]
[2025-03-11 10:41:49,915] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:56517]
[2025-03-11 10:41:49,939] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:56517]
[2025-03-11 10:41:50,001] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:56520]
[2025-03-11 10:41:50,088] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:56520]
[2025-03-11 10:41:50,120] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:56517]
[2025-03-11 10:41:50,176] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:56517]
[2025-03-11 10:41:50,772] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 195, in SubscriptionStatus_view
    for monthly_total in monthly_totals:
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 268, in __iter__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1017, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1052, in execute_sql
    sql, params = self.as_sql()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 449, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 50, in pre_sql_setup
    self.setup_query()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 41, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 244, in get_select
    sql, params = self.compile(col, select_format=True)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 388, in compile
    sql, params = vendor_impl(self, self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 162, in as_mysql
    if self.output_field.get_internal_type() == 'DurationField':
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 256, in output_field
    output_field = self._resolve_output_field()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 288, in _resolve_output_field
    sources_iter = (source for source in self.get_source_fields() if source is not None)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 25, in get_source_fields
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\aggregates.py", line 25, in <listcomp>
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 269, in _output_field_or_none
    return self.output_field
  File "C:\Python372\mecheck\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 256, in output_field
    output_field = self._resolve_output_field()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\expressions.py", line 291, in _resolve_output_field
    raise FieldError('Expression contains mixed types. You must set output_field.')
django.core.exceptions.FieldError: Expression contains mixed types. You must set output_field.
[2025-03-11 10:41:50,785] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:50: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:41:50,788] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.50, 127.0.0.1:56517]
[2025-03-11 10:41:50,821] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:41:50: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:41:50,853] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.55, 127.0.0.1:56518]
[2025-03-11 10:44:53,624] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:44:53: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:44:53,654] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:56875]
[2025-03-11 10:44:53,772] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:56875]
[2025-03-11 10:44:53,798] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:56875]
[2025-03-11 10:44:53,839] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:56879]
[2025-03-11 10:44:53,899] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:56879]
[2025-03-11 10:44:53,918] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:56875]
[2025-03-11 10:44:53,922] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:56876]
[2025-03-11 10:44:54,130] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:44:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:44:54,140] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:56876]
[2025-03-11 10:44:54,167] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:44:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:44:54,196] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.15, 127.0.0.1:56875]
[2025-03-11 10:45:44,617] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:45:44: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:45:44,626] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:56875]
[2025-03-11 10:45:44,634] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:56879]
[2025-03-11 10:45:44,703] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:56875]
[2025-03-11 10:45:44,714] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:56875]
[2025-03-11 10:45:44,760] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:56958]
[2025-03-11 10:45:44,763] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:56958]
[2025-03-11 10:45:44,836] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:56875]
[2025-03-11 10:45:44,839] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:56876]
[2025-03-11 10:45:44,963] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:45:44: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:45:44,971] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:56876]
[2025-03-11 10:45:44,981] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:45:44: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:45:45,000] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:56875]
[2025-03-11 10:47:34,676] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:47:34: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:47:34,707] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:57155]
[2025-03-11 10:48:20,703] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:48:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:48:20,712] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.08, 127.0.0.1:57230]
[2025-03-11 10:48:20,776] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:57230]
[2025-03-11 10:48:20,786] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:57230]
[2025-03-11 10:48:20,797] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:57233]
[2025-03-11 10:48:20,853] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:57231]
[2025-03-11 10:48:20,858] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:57230]
[2025-03-11 10:48:20,860] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:57233]
[2025-03-11 10:48:20,915] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:48:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 10:48:20,929] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:57230]
[2025-03-11 10:48:20,940] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 10:48:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 10:48:20,968] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:57231]
[2025-03-11 11:02:12,993] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:02:12: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:02:13,030] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.24, 127.0.0.1:58769]
[2025-03-11 11:02:13,144] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:58769]
[2025-03-11 11:02:13,173] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:58769]
[2025-03-11 11:02:13,203] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:58773]
[2025-03-11 11:02:13,381] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:58769]
[2025-03-11 11:02:13,389] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:58770]
[2025-03-11 11:02:13,392] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:58773]
[2025-03-11 11:02:13,427] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:02:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:02:13,438] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:58770]
[2025-03-11 11:02:13,457] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:02:13: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:02:13,495] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:58769]
[2025-03-11 11:02:51,039] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:02:51: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:02:51,063] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:58769]
[2025-03-11 11:14:46,244] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 104, in SubscriptionStatus_view
    SubscriptionStatus.objects.create(**Add_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 'undefined'
[2025-03-11 11:14:46,273] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:14:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:14:46,298] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [1.52, 127.0.0.1:60173]
[2025-03-11 11:15:35,782] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 105, in SubscriptionStatus_view
    SubscriptionStatus.objects.create(**Add_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1288, in execute_sql
    for sql, params in self.as_sql():
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in as_sql
    for obj in self.query.objs
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1241, in <listcomp>
    for obj in self.query.objs
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1240, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1182, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 790, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 785, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 1737, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 'undefined'
[2025-03-11 11:15:35,793] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:15:35: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:15:35,803] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.45, 127.0.0.1:60267]
[2025-03-11 11:16:29,121] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:16:29: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:16:29,138] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.12, 127.0.0.1:60371]
[2025-03-11 11:17:38,723] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:38: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-11 11:17:38,740] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.43, 127.0.0.1:60485]
[2025-03-11 11:17:38,892] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:38: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/'>
[2025-03-11 11:17:38,905] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.16, 127.0.0.1:60485]
[2025-03-11 11:17:39,090] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:17:39,147] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:60485]
[2025-03-11 11:17:42,345] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:42: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/login/?next=/admin/'>
[2025-03-11 11:17:42,363] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.49, 127.0.0.1:60485]
[2025-03-11 11:17:44,751] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:44: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-11 11:17:44,784] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [2.41, 127.0.0.1:60485]
[2025-03-11 11:17:45,030] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:45: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:17:45,073] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:60485]
[2025-03-11 11:17:49,793] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:49: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/menu/'>
[2025-03-11 11:17:49,809] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/menu/ 200 [0.49, 127.0.0.1:60485]
[2025-03-11 11:17:49,864] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:49: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:17:49,901] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.55, 127.0.0.1:60486]
[2025-03-11 11:17:49,908] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/simpleui-x/css/base.css?_=2.7 304 [0.07, 127.0.0.1:60485]
[2025-03-11 11:17:49,927] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:49: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-11 11:17:49,941] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:60512]
[2025-03-11 11:17:59,953] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:59: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/MiscellaneousPurchases/subscriptionstatus/'>
[2025-03-11 11:17:59,969] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/MiscellaneousPurchases/subscriptionstatus/ 200 [0.18, 127.0.0.1:60512]
[2025-03-11 11:18:00,002] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:17:59: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:18:00,047] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.23, 127.0.0.1:60485]
[2025-03-11 11:18:00,073] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:18:00: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-11 11:18:00,106] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.12, 127.0.0.1:60512]
[2025-03-11 11:19:01,579] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:01: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:19:01,607] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:60683]
[2025-03-11 11:19:01,898] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:60683]
[2025-03-11 11:19:01,942] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:60683]
[2025-03-11 11:19:02,097] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60688]
[2025-03-11 11:19:02,152] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60688]
[2025-03-11 11:19:02,286] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:60683]
[2025-03-11 11:19:02,301] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.00, 127.0.0.1:60683]
[2025-03-11 11:19:03,009] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 231, in SubscriptionStatus_view
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-11 11:19:03,013] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:03: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:19:03,015] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.31, 127.0.0.1:60683]
[2025-03-11 11:19:03,039] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:03: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:19:03,080] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.35, 127.0.0.1:60684]
[2025-03-11 11:19:16,030] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:19:16,048] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:60684]
[2025-03-11 11:19:16,056] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60688]
[2025-03-11 11:19:16,121] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:60684]
[2025-03-11 11:19:16,132] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:60684]
[2025-03-11 11:19:16,177] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60725]
[2025-03-11 11:19:16,180] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60725]
[2025-03-11 11:19:16,248] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:60684]
[2025-03-11 11:19:16,252] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:60683]
[2025-03-11 11:19:16,384] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 231, in SubscriptionStatus_view
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-11 11:19:16,386] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:19:16,388] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.06, 127.0.0.1:60683]
[2025-03-11 11:19:16,424] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:19:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:19:16,458] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:60684]
[2025-03-11 11:20:50,248] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:20:50: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:20:50,278] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:60991]
[2025-03-11 11:20:50,348] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:60991]
[2025-03-11 11:20:50,359] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:60991]
[2025-03-11 11:20:50,371] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:60994]
[2025-03-11 11:20:50,418] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:60991]
[2025-03-11 11:20:50,424] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:60992]
[2025-03-11 11:20:50,426] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:60994]
[2025-03-11 11:20:50,742] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 230, in SubscriptionStatus_view
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-11 11:20:50,746] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:20:50: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:20:50,747] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.28, 127.0.0.1:60992]
[2025-03-11 11:20:50,757] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:20:50: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:20:50,778] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.30, 127.0.0.1:60991]
[2025-03-11 11:21:54,149] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:21:54: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:21:54,166] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.11, 127.0.0.1:61121]
[2025-03-11 11:21:54,247] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61121]
[2025-03-11 11:21:54,261] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:61121]
[2025-03-11 11:21:54,276] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61124]
[2025-03-11 11:21:54,337] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61121]
[2025-03-11 11:21:54,343] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61122]
[2025-03-11 11:21:54,346] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61124]
[2025-03-11 11:21:54,807] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 230, in SubscriptionStatus_view
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-11 11:21:54,812] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:21:54: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:21:54,815] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.40, 127.0.0.1:61122]
[2025-03-11 11:21:54,827] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:21:54: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:21:54,863] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.44, 127.0.0.1:61121]
[2025-03-11 11:22:37,002] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:22:37: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:22:37,029] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.10, 127.0.0.1:61216]
[2025-03-11 11:22:37,142] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:61216]
[2025-03-11 11:22:37,154] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:61216]
[2025-03-11 11:22:37,171] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61219]
[2025-03-11 11:22:37,234] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61216]
[2025-03-11 11:22:37,241] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61217]
[2025-03-11 11:22:37,244] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61219]
[2025-03-11 11:22:37,721] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 231, in SubscriptionStatus_view
    return HttpResponse(json.dumps(data), content_type="application/json")
  File "C:\Python372\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python372\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python372\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python372\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
[2025-03-11 11:22:37,726] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:22:37: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:22:37,728] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.42, 127.0.0.1:61217]
[2025-03-11 11:22:37,760] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:22:37: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:22:37,796] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.47, 127.0.0.1:61216]
[2025-03-11 11:23:47,728] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:23:47: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:23:47,766] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.11, 127.0.0.1:61343]
[2025-03-11 11:23:48,033] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61343]
[2025-03-11 11:23:48,070] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61343]
[2025-03-11 11:23:48,161] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61347]
[2025-03-11 11:23:48,222] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61347]
[2025-03-11 11:23:48,253] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:61343]
[2025-03-11 11:23:48,257] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61344]
[2025-03-11 11:23:48,610] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:23:48: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:23:48,630] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:61344]
[2025-03-11 11:23:48,660] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:23:48: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:23:48,700] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:61343]
[2025-03-11 11:28:58,494] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:28:58: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:28:58,511] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:61914]
[2025-03-11 11:28:58,586] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:61914]
[2025-03-11 11:28:58,600] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61914]
[2025-03-11 11:28:58,614] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61923]
[2025-03-11 11:28:58,685] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61914]
[2025-03-11 11:28:58,692] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61915]
[2025-03-11 11:28:58,695] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61923]
[2025-03-11 11:28:58,769] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:28:58: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:28:58,781] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:61915]
[2025-03-11 11:28:58,807] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:28:58: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:28:58,837] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:61914]
[2025-03-11 11:29:57,582] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:29:57: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:29:57,619] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.15, 127.0.0.1:62043]
[2025-03-11 11:30:12,489] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:30:12: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:30:12,519] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:62043]
[2025-03-11 11:31:57,246] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:31:57: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:31:57,263] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:62278]
[2025-03-11 11:32:02,709] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 130, in SubscriptionStatus_view
    SubscriptionStatus.objects.filter(id=update_dic).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 965, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
[2025-03-11 11:32:02,732] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:32:02: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:32:02,736] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [1.06, 127.0.0.1:62278]
[2025-03-11 11:33:04,708] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 130, in SubscriptionStatus_view
    SubscriptionStatus.objects.filter(id=update_dic).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 965, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
[2025-03-11 11:33:04,715] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:33:04: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:33:04,724] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.35, 127.0.0.1:62413]
[2025-03-11 11:34:04,920] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/SubscriptionStatus/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 130, in SubscriptionStatus_view
    SubscriptionStatus.objects.filter(id=update_dic).update(**update_dic)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\lookups.py", line 70, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\fields\__init__.py", line 965, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
[2025-03-11 11:34:04,927] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:34:04: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:34:04,934] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 500 [0.30, 127.0.0.1:62528]
[2025-03-11 11:36:16,393] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:36:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:36:16,409] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:62850]
[2025-03-11 11:41:06,220] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:06: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:41:06,243] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:63360]
[2025-03-11 11:41:06,348] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63360]
[2025-03-11 11:41:06,366] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63360]
[2025-03-11 11:41:06,425] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63363]
[2025-03-11 11:41:06,519] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63363]
[2025-03-11 11:41:06,536] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63360]
[2025-03-11 11:41:06,541] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63361]
[2025-03-11 11:41:06,746] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:06: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:41:06,769] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:63361]
[2025-03-11 11:41:06,792] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:06: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:41:06,826] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:63360]
[2025-03-11 11:41:31,358] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:31: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:41:31,389] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:63420]
[2025-03-11 11:41:31,478] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:63420]
[2025-03-11 11:41:31,488] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:63420]
[2025-03-11 11:41:31,539] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63424]
[2025-03-11 11:41:31,605] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63424]
[2025-03-11 11:41:31,628] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63420]
[2025-03-11 11:41:31,675] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63420]
[2025-03-11 11:41:31,801] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:31: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:41:31,818] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.05, 127.0.0.1:63420]
[2025-03-11 11:41:31,846] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:41:31: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:41:31,884] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:63421]
[2025-03-11 11:44:09,850] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:44:09: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:44:09,862] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:63709]
[2025-03-11 11:44:09,953] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:63709]
[2025-03-11 11:44:09,978] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63709]
[2025-03-11 11:44:10,014] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63713]
[2025-03-11 11:44:10,069] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63713]
[2025-03-11 11:44:10,090] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63709]
[2025-03-11 11:44:10,095] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63710]
[2025-03-11 11:44:10,224] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:44:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:44:10,234] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.02, 127.0.0.1:63710]
[2025-03-11 11:44:10,254] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:44:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:44:10,283] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:63709]
[2025-03-11 11:47:07,614] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:47:07: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:47:07,626] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:64055]
[2025-03-11 11:47:14,108] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:47:14: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:47:14,127] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:64055]
[2025-03-11 11:49:10,206] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:49:10,215] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.04, 127.0.0.1:64264]
[2025-03-11 11:49:16,055] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-11 11:49:16,094] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [2.40, 127.0.0.1:64264]
[2025-03-11 11:49:16,515] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/MiscellaneousPurchases/subscriptionstatus/'>
[2025-03-11 11:49:16,535] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/MiscellaneousPurchases/subscriptionstatus/ 200 [0.30, 127.0.0.1:64264]
[2025-03-11 11:49:16,585] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-11 11:49:16,599] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:64264]
[2025-03-11 11:49:16,727] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 11:49:16,762] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:64264]
[2025-03-11 11:49:18,109] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:18: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/MiscellaneousPurchases/subscriptionstatus/2/change/'>
[2025-03-11 11:49:18,125] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/MiscellaneousPurchases/subscriptionstatus/2/change/ 200 [0.31, 127.0.0.1:64264]
[2025-03-11 11:49:18,160] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:18: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-11 11:49:18,173] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.03, 127.0.0.1:64264]
[2025-03-11 11:49:18,178] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/calendar.js 304 [0.03, 127.0.0.1:64272]
[2025-03-11 11:49:18,182] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/js/admin/DateTimeShortcuts.js 304 [0.03, 127.0.0.1:64300]
[2025-03-11 11:49:18,242] [runserver.py:145] [runserver:log_action] [INFO]- HTTP GET /static/admin/img/icon-calendar.svg 304 [0.01, 127.0.0.1:64300]
[2025-03-11 11:49:26,269] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:26: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/MiscellaneousPurchases/subscriptionstatus/'>
[2025-03-11 11:49:26,304] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/MiscellaneousPurchases/subscriptionstatus/ 200 [0.27, 127.0.0.1:64300]
[2025-03-11 11:49:53,788] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:49:53: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:49:53,801] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:64300]
[2025-03-11 11:51:39,987] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:51:39: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:51:40,002] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.24, 127.0.0.1:64673]
[2025-03-11 11:53:38,178] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:53:38: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:53:38,212] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.16, 127.0.0.1:64968]
[2025-03-11 11:53:55,146] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:53:55: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:53:55,183] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:64968]
[2025-03-11 11:54:02,015] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:54:02: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:54:02,036] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:64968]
[2025-03-11 11:54:16,871] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:54:16: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:54:16,888] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.05, 127.0.0.1:64968]
[2025-03-11 11:54:22,799] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:54:22: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:54:22,820] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:64968]
[2025-03-11 11:54:31,231] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 11:54:31: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 11:54:31,253] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:64968]
[2025-03-11 13:06:53,936] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:06:53: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:06:53,977] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.11, 127.0.0.1:55313]
[2025-03-11 13:06:54,100] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:55313]
[2025-03-11 13:06:54,121] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:55313]
[2025-03-11 13:06:54,157] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:55316]
[2025-03-11 13:06:54,211] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55316]
[2025-03-11 13:06:54,240] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:55313]
[2025-03-11 13:06:54,245] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:55314]
[2025-03-11 13:06:54,397] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:06:54: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:06:54,410] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:55314]
[2025-03-11 13:06:54,444] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:06:54: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 13:06:54,477] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:55313]
[2025-03-11 13:07:02,992] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:07:02: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:07:03,010] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.05, 127.0.0.1:55313]
[2025-03-11 13:10:03,415] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:10:03: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:10:03,434] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.09, 127.0.0.1:55617]
[2025-03-11 13:10:03,507] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:55617]
[2025-03-11 13:10:03,516] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:55617]
[2025-03-11 13:10:03,562] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:55620]
[2025-03-11 13:10:03,617] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55620]
[2025-03-11 13:10:03,643] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:55617]
[2025-03-11 13:10:03,647] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:55618]
[2025-03-11 13:10:03,771] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:10:03: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:10:03,784] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.03, 127.0.0.1:55618]
[2025-03-11 13:10:03,807] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:10:03: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 13:10:03,840] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:55617]
[2025-03-11 13:10:10,340] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:10:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-11 13:10:10,366] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.07, 127.0.0.1:55617]
[2025-03-11 13:33:32,698] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:33:32: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-11 13:33:32,736] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET / 200 [0.11, 127.0.0.1:58015]
[2025-03-11 13:33:33,327] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:58018]
[2025-03-11 13:33:33,373] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:58018]
[2025-03-11 13:33:33,608] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:33:33: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/PermInfo/'>
[2025-03-11 13:33:33,621] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /PermInfo/ 200 [0.04, 127.0.0.1:58015]
[2025-03-11 13:33:33,661] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-11 13:33:33: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-11 13:33:33,682] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.03, 127.0.0.1:58015]
[2025-03-11 13:33:35,942] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:58018]
