[2025-03-04 09:56:53,801] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 09:56:53 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/api/login/ POST
[2025-03-04 09:56:53,819] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CQM/api/login/ 200 [0.29, 127.0.0.1:53091]
[2025-03-04 09:58:01,130] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 09:58:01 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/CQMapi/ GET
[2025-03-04 09:58:01,144] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.25, 127.0.0.1:53175]
[2025-03-04 10:08:03,982] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:08:03 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/CQMapi/ GET
[2025-03-04 10:08:03,994] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.19, 127.0.0.1:50560]
[2025-03-04 10:09:34,074] [UserIP.py:90] [UserIP:process_response] [INFO]- 2025-03-04 10:09:34 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/CQMapi/ GET
[2025-03-04 10:09:34,086] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.19, 127.0.0.1:52063]
[2025-03-04 10:18:39,634] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:18:39 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/api/login/ POST
[2025-03-04 10:18:39,650] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CQM/api/login/ 200 [0.13, 127.0.0.1:59234]
[2025-03-04 10:18:55,027] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:18:55 API_CQM>API_CQM None>None>None 127.0.0.1 127.0.0.1 /CQM/CQMapi/ GET
[2025-03-04 10:18:55,038] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.20, 127.0.0.1:59234]
[2025-03-04 10:49:57,216] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:49:57: API_CQM-AnonymousUser-API_CQM> None-None-None > 127.0.0.1-127.0.0.1 > <AsgiRequest: GET '/CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT'>
[2025-03-04 10:49:57,225] [log.py:228] [log:log_response] [WARNING]- Unauthorized: /CQM/CQMapi/
[2025-03-04 10:49:57,226] [runserver.py:151] [runserver:log_action] [WARNING]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 401 [0.08, 127.0.0.1:61800]
[2025-03-04 10:50:45,727] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:50:45: API_CQM-AnonymousUser-API_CQM> None-None-None > 127.0.0.1-127.0.0.1 > <AsgiRequest: POST '/CQM/api/login/'>
[2025-03-04 10:50:45,742] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /CQM/api/login/ 200 [0.05, 127.0.0.1:61800]
[2025-03-04 10:50:58,291] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:50:58: API_CQM-API_CQM-API_CQM> None-None-None > 127.0.0.1-127.0.0.1 > <AsgiRequest: GET '/CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT'>
[2025-03-04 10:50:58,298] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.21, 127.0.0.1:61800]
[2025-03-04 10:53:11,676] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 10:53:11: API_CQM/API_CQM/API_CQM> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT'>
[2025-03-04 10:53:11,684] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /CQM/CQMapi/?Customer=C38(NB)&Project=GLMS1&Phase=SIT 200 [0.18, 127.0.0.1:62035]
[2025-03-04 11:01:58,501] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:01:58: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/ProjectComparison/ProjectComparison_Summary/'>
[2025-03-04 11:01:58,504] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /ProjectComparison/ProjectComparison_Summary/ 302 [0.10, 127.0.0.1:63034]
[2025-03-04 11:01:58,596] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:01:58: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 11:01:58,600] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.09, 127.0.0.1:63034]
[2025-03-04 11:01:58,830] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:01:58: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:01:58,834] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.12, 127.0.0.1:63034]
[2025-03-04 11:01:58,848] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:01:58: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 11:01:58,852] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:63034]
[2025-03-04 11:02:00,662] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:00: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/login/?next='>
[2025-03-04 11:02:00,690] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /login/?next= 302 [0.09, 127.0.0.1:63034]
[2025-03-04 11:02:00,714] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:00: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 11:02:00,741] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /login/ 302 [0.04, 127.0.0.1:63034]
[2025-03-04 11:02:01,029] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:01: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 11:02:01,071] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.32, 127.0.0.1:63034]
[2025-03-04 11:02:01,428] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63041]
[2025-03-04 11:02:02,039] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63041]
[2025-03-04 11:02:02,041] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:02: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:02,147] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.14, 127.0.0.1:63034]
[2025-03-04 11:02:23,635] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/Property/'>
[2025-03-04 11:02:23,657] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Property/ 200 [0.13, 127.0.0.1:63034]
[2025-03-04 11:02:23,747] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/Property/'>
[2025-03-04 11:02:23,767] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Property/ 200 [0.08, 127.0.0.1:63034]
[2025-03-04 11:02:23,872] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63041]
[2025-03-04 11:02:23,945] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63072]
[2025-03-04 11:02:23,959] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63072]
[2025-03-04 11:02:24,183] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:24: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/Navigations_Category/'>
[2025-03-04 11:02:24,248] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_Category/ 200 [0.11, 127.0.0.1:63034]
[2025-03-04 11:02:24,464] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:24: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:24,618] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.47, 127.0.0.1:63033]
[2025-03-04 11:02:29,034] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:29: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 11:02:29,058] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.05, 127.0.0.1:63033]
[2025-03-04 11:02:29,117] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63072]
[2025-03-04 11:02:29,158] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63090]
[2025-03-04 11:02:29,241] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63090]
[2025-03-04 11:02:29,328] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:29: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:29,398] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:63033]
[2025-03-04 11:02:30,497] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:30: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/Budget/'>
[2025-03-04 11:02:30,533] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Budget/ 200 [0.06, 127.0.0.1:63033]
[2025-03-04 11:02:30,581] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:30: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/Budget/'>
[2025-03-04 11:02:30,602] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/Budget/ 200 [0.05, 127.0.0.1:63033]
[2025-03-04 11:02:30,666] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63090]
[2025-03-04 11:02:30,698] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63097]
[2025-03-04 11:02:30,743] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63097]
[2025-03-04 11:02:30,809] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:30: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/Navigations_Category/'>
[2025-03-04 11:02:30,856] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_Category/ 200 [0.07, 127.0.0.1:63033]
[2025-03-04 11:02:30,885] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:30: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:30,917] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:63034]
[2025-03-04 11:02:33,327] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:33: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_system/MiscellaneousPurchases/'>
[2025-03-04 11:02:33,344] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/MiscellaneousPurchases/ 200 [0.09, 127.0.0.1:63034]
[2025-03-04 11:02:33,394] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:33: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_system/MiscellaneousPurchases/'>
[2025-03-04 11:02:33,416] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/MiscellaneousPurchases/ 200 [0.05, 127.0.0.1:63034]
[2025-03-04 11:02:33,491] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63097]
[2025-03-04 11:02:33,514] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63107]
[2025-03-04 11:02:33,562] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63107]
[2025-03-04 11:02:33,656] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:33: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/Navigations_system/'>
[2025-03-04 11:02:33,700] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_system/ 200 [0.07, 127.0.0.1:63034]
[2025-03-04 11:02:33,778] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:33: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:33,834] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.16, 127.0.0.1:63033]
[2025-03-04 11:02:35,248] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:35: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/SubscriptionStatus/'>
[2025-03-04 11:02:35,265] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/SubscriptionStatus/ 200 [0.06, 127.0.0.1:63033]
[2025-03-04 11:02:35,347] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:35: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:35,380] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:63033]
[2025-03-04 11:02:55,050] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:02:55,098] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.15, 127.0.0.1:63033]
[2025-03-04 11:02:55,132] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63107]
[2025-03-04 11:02:55,257] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59208]
[2025-03-04 11:02:55,262] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59208]
[2025-03-04 11:02:57,356] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:57: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/PersonalInfo/PersonalInfo-edit/'>
[2025-03-04 11:02:57,397] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /PersonalInfo/PersonalInfo-edit/ 200 [1.89, 127.0.0.1:63033]
[2025-03-04 11:02:57,416] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:02:57: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:02:57,457] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [1.92, 127.0.0.1:63034]
[2025-03-04 11:04:27,242] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:04:27,257] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:59329]
[2025-03-04 11:04:27,320] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59208]
[2025-03-04 11:04:27,406] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59333]
[2025-03-04 11:04:27,408] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59333]
[2025-03-04 11:04:27,578] [log.py:228] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /MiscellaneousPurchases/Budget/
[2025-03-04 11:04:27,598] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:04:27,624] [runserver.py:151] [runserver:log_action] [WARNING]- HTTP POST /MiscellaneousPurchases/Budget/ 403 [0.07, 127.0.0.1:59329]
[2025-03-04 11:04:27,633] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:04:27,660] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:59330]
[2025-03-04 11:04:46,629] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.10, 127.0.0.1:59330]
[2025-03-04 11:04:46,679] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.15, 127.0.0.1:59329]
[2025-03-04 11:04:46,721] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.16, 127.0.0.1:59390]
[2025-03-04 11:04:46,759] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.16, 127.0.0.1:59391]
[2025-03-04 11:04:48,839] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:48: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:04:48,884] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.11, 127.0.0.1:59391]
[2025-03-04 11:04:48,899] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59333]
[2025-03-04 11:04:49,142] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.10, 127.0.0.1:59391]
[2025-03-04 11:04:49,181] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59399]
[2025-03-04 11:04:49,245] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.17, 127.0.0.1:59390]
[2025-03-04 11:04:49,489] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59399]
[2025-03-04 11:04:49,518] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.17, 127.0.0.1:59390]
[2025-03-04 11:04:49,553] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.08, 127.0.0.1:59391]
[2025-03-04 11:04:49,618] [log.py:228] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /MiscellaneousPurchases/Budget/
[2025-03-04 11:04:49,640] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:49: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:04:49,686] [runserver.py:151] [runserver:log_action] [WARNING]- HTTP POST /MiscellaneousPurchases/Budget/ 403 [0.10, 127.0.0.1:59391]
[2025-03-04 11:04:49,743] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:04:49: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:04:49,796] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.19, 127.0.0.1:59390]
[2025-03-04 11:05:53,971] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:05:53: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_system/MiscellaneousPurchases/'>
[2025-03-04 11:05:53,982] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_system/MiscellaneousPurchases/ 200 [0.11, 127.0.0.1:59588]
[2025-03-04 11:05:54,094] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:59588]
[2025-03-04 11:05:54,104] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:05:54,189] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59592]
[2025-03-04 11:05:54,419] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:05:54,425] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.02, 127.0.0.1:59588]
[2025-03-04 11:05:54,504] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59592]
[2025-03-04 11:05:54,550] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:05:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/Navigations_system/'>
[2025-03-04 11:05:54,581] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_system/ 200 [0.05, 127.0.0.1:59588]
[2025-03-04 11:05:54,611] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:05:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:05:54,641] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:59587]
[2025-03-04 11:06:03,454] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:06:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:06:03,490] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.08, 127.0.0.1:59587]
[2025-03-04 11:06:03,661] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59592]
[2025-03-04 11:06:03,672] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:06:03,708] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:06:03,825] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59640]
[2025-03-04 11:06:03,838] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59640]
[2025-03-04 11:06:03,992] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:06:04,103] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:59587]
[2025-03-04 11:06:04,328] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:06:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:06:04,362] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.09, 127.0.0.1:59587]
[2025-03-04 11:06:04,387] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:06:04: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:06:04,449] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.14, 127.0.0.1:59588]
[2025-03-04 11:07:22,785] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:07:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:07:22,815] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.12, 127.0.0.1:59799]
[2025-03-04 11:07:23,031] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:59799]
[2025-03-04 11:07:23,082] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:59799]
[2025-03-04 11:07:23,154] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:59801]
[2025-03-04 11:07:23,260] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:59801]
[2025-03-04 11:07:23,270] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:59799]
[2025-03-04 11:07:23,336] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:59799]
[2025-03-04 11:07:23,488] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:07:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:07:23,501] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:59799]
[2025-03-04 11:07:23,514] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:07:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:07:23,554] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:59797]
[2025-03-04 11:17:17,937] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 90, in Budget
    for i in Budget.objects.all().values("Year"):
AttributeError: 'function' object has no attribute 'objects'
[2025-03-04 11:17:17,951] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:17:17: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:17:17,989] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [7.16, 127.0.0.1:61248]
[2025-03-04 11:17:18,241] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:17:18: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:17:18,376] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.24, 127.0.0.1:61248]
[2025-03-04 11:20:02,931] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 92, in Budget
    for i in Budget.objects.all().values("Year").distinct().order_by("Year"):
AttributeError: 'function' object has no attribute 'objects'
[2025-03-04 11:20:02,937] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:20:02: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:20:02,948] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [0.58, 127.0.0.1:61631]
[2025-03-04 11:20:03,033] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:20:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:20:03,094] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:61631]
[2025-03-04 11:21:47,855] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 92, in Budget
    for i in Budget.objects.all().values("Year").distinct().order_by("Year"):
AttributeError: 'function' object has no attribute 'objects'
[2025-03-04 11:21:47,858] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:21:47: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:21:47,866] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [0.40, 127.0.0.1:61957]
[2025-03-04 11:21:47,971] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:21:47: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:21:48,006] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:61957]
[2025-03-04 11:22:43,490] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 92, in Budget
    for i in Budget.objects.all().values("Year").distinct().order_by("Year"):
AttributeError: 'function' object has no attribute 'objects'
[2025-03-04 11:22:43,495] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:22:43: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:22:43,511] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [0.42, 127.0.0.1:62133]
[2025-03-04 11:22:43,601] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:22:43: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:22:43,628] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:62133]
[2025-03-04 11:25:57,767] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'reliabilityrowdata.miscellaneouspurchases_budget' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 92, in Budget_view
    for i in Budget.objects.all().values("Year").distinct().order_by("Year"):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 268, in __iter__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1017, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'reliabilityrowdata.miscellaneouspurchases_budget' doesn't exist")
[2025-03-04 11:25:57,786] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:25:57: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:25:57,796] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [0.61, 127.0.0.1:62585]
[2025-03-04 11:25:57,925] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:25:57: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:25:57,961] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:62585]
[2025-03-04 11:28:39,031] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'reliabilityrowdata.miscellaneouspurchases_budget' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 92, in Budget_view
    for i in Budget.objects.all().values("Year").distinct().order_by("Year"):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 268, in __iter__
    self._fetch_all()
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1017, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "C:\Python372\mecheck\lib\site-packages\django\db\models\sql\compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Python372\mecheck\lib\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 170, in execute
    result = self._query(query)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 732, in _read_query_result
    result.read()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\connections.py", line 684, in _read_packet
    packet.check_error()
  File "C:\Python372\mecheck\lib\site-packages\pymysql\protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "C:\Python372\mecheck\lib\site-packages\pymysql\err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'reliabilityrowdata.miscellaneouspurchases_budget' doesn't exist")
[2025-03-04 11:28:39,050] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:28:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:28:39,058] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [0.46, 127.0.0.1:62941]
[2025-03-04 11:28:39,220] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:28:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:28:39,268] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:62941]
[2025-03-04 11:31:21,476] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:31:21: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:31:21,492] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.16, 127.0.0.1:63439]
[2025-03-04 11:31:21,911] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63439]
[2025-03-04 11:31:21,916] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63438]
[2025-03-04 11:31:21,946] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63444]
[2025-03-04 11:31:22,100] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:63438]
[2025-03-04 11:31:22,103] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63444]
[2025-03-04 11:31:22,190] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63439]
[2025-03-04 11:31:22,292] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:31:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:31:22,317] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:63439]
[2025-03-04 11:31:22,345] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:31:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:31:22,429] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.12, 127.0.0.1:63438]
[2025-03-04 11:32:27,146] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:32:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:32:27,160] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.12, 127.0.0.1:63728]
[2025-03-04 11:32:27,403] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63737]
[2025-03-04 11:32:27,526] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:63728]
[2025-03-04 11:32:27,533] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:63729]
[2025-03-04 11:32:27,539] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.02, 127.0.0.1:63731]
[2025-03-04 11:32:27,540] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63737]
[2025-03-04 11:32:27,579] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63728]
[2025-03-04 11:32:27,757] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:32:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:32:27,788] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.09, 127.0.0.1:63728]
[2025-03-04 11:32:27,799] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:32:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:32:27,833] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:63731]
[2025-03-04 11:36:21,466] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:36:21: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:36:21,496] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.11, 127.0.0.1:64657]
[2025-03-04 11:36:21,732] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64660]
[2025-03-04 11:36:22,028] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64660]
[2025-03-04 11:36:22,029] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:64656]
[2025-03-04 11:36:22,037] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.02, 127.0.0.1:64657]
[2025-03-04 11:36:22,046] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.03, 127.0.0.1:64663]
[2025-03-04 11:36:22,192] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64664]
[2025-03-04 11:36:22,228] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:36:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:36:22,295] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.10, 127.0.0.1:64667]
[2025-03-04 11:36:22,313] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:36:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:36:22,395] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.11, 127.0.0.1:64664]
[2025-03-04 11:36:46,618] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:36:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:36:46,776] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.44, 127.0.0.1:64761]
[2025-03-04 11:39:35,937] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:39:35: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:39:35,992] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.28, 127.0.0.1:65386]
[2025-03-04 11:50:53,385] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:50:53: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:50:53,415] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.10, 127.0.0.1:52470]
[2025-03-04 11:50:53,756] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52470]
[2025-03-04 11:50:53,785] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52470]
[2025-03-04 11:50:53,911] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52476]
[2025-03-04 11:50:54,076] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52476]
[2025-03-04 11:50:54,262] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:52470]
[2025-03-04 11:50:54,566] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52470]
[2025-03-04 11:50:55,078] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:50:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:50:55,185] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.16, 127.0.0.1:52470]
[2025-03-04 11:50:55,223] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:50:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 11:50:55,416] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.22, 127.0.0.1:52471]
[2025-03-04 11:51:00,021] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:51:00: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:51:00,102] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.20, 127.0.0.1:52471]
[2025-03-04 11:51:34,174] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 11:51:34: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 11:51:34,190] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.12, 127.0.0.1:52471]
[2025-03-04 12:59:30,686] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 12:59:30: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 12:59:30,724] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.20, 127.0.0.1:61504]
[2025-03-04 12:59:39,471] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 93, in Budget_view
    yearOptions.append(i.Year)
AttributeError: 'dict' object has no attribute 'Year'
[2025-03-04 12:59:39,479] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 12:59:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 12:59:39,482] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /MiscellaneousPurchases/Budget/ 500 [1.08, 127.0.0.1:61504]
[2025-03-04 12:59:39,561] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 12:59:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 12:59:39,613] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.09, 127.0.0.1:61504]
[2025-03-04 13:01:46,111] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:01:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:01:46,121] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.14, 127.0.0.1:61719]
[2025-03-04 13:01:46,245] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61719]
[2025-03-04 13:01:46,275] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61719]
[2025-03-04 13:01:46,292] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61723]
[2025-03-04 13:01:46,374] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61720]
[2025-03-04 13:01:46,381] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61719]
[2025-03-04 13:01:46,384] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61723]
[2025-03-04 13:01:46,465] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:01:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:01:46,478] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.02, 127.0.0.1:61719]
[2025-03-04 13:01:46,490] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:01:46: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 13:01:46,511] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.04, 127.0.0.1:61720]
[2025-03-04 13:02:45,194] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:02:45: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:02:45,237] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.21, 127.0.0.1:61817]
[2025-03-04 13:03:22,427] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:03:22: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:03:22,459] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.06, 127.0.0.1:61817]
[2025-03-04 13:11:19,780] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:11:19: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:11:19,807] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.09, 127.0.0.1:62568]
[2025-03-04 13:11:19,913] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:62568]
[2025-03-04 13:11:19,935] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:62568]
[2025-03-04 13:11:19,980] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:62571]
[2025-03-04 13:11:20,072] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62571]
[2025-03-04 13:11:20,084] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:62568]
[2025-03-04 13:11:20,092] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:62569]
[2025-03-04 13:11:20,232] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:11:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:11:20,244] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:62569]
[2025-03-04 13:11:20,276] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:11:20: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 13:11:20,290] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:62568]
[2025-03-04 13:11:27,706] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:11:27: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:11:27,725] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:62568]
[2025-03-04 13:11:40,284] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:11:40: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:11:40,296] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.05, 127.0.0.1:62568]
[2025-03-04 13:12:17,719] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:12:17: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:12:17,732] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.07, 127.0.0.1:62568]
[2025-03-04 13:12:28,409] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:12:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:12:28,446] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.07, 127.0.0.1:62568]
[2025-03-04 13:17:25,315] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:17:25: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:17:25,348] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.06, 127.0.0.1:63284]
[2025-03-04 13:17:25,358] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62571]
[2025-03-04 13:17:25,429] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:63284]
[2025-03-04 13:17:25,443] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:63284]
[2025-03-04 13:17:25,494] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:63287]
[2025-03-04 13:17:25,497] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:63287]
[2025-03-04 13:17:25,597] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:63284]
[2025-03-04 13:17:25,608] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:63284]
[2025-03-04 13:17:25,719] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:17:25: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:17:25,740] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:63284]
[2025-03-04 13:17:25,763] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:17:25: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 13:17:25,780] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:63285]
[2025-03-04 13:18:15,577] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:18:15: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:18:15,589] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.05, 127.0.0.1:63285]
[2025-03-04 13:18:19,346] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:18:19: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:18:19,381] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.07, 127.0.0.1:63285]
[2025-03-04 13:20:03,108] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:20:03: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:20:03,163] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.20, 127.0.0.1:63542]
[2025-03-04 13:21:06,815] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /MiscellaneousPurchases/Budget/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python372\mecheck\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\djangoproject\Reliability_Row_data\MiscellaneousPurchases\views.py", line 149, in Budget_view
    if Budget.objects.filter(**check_dic):
UnboundLocalError: local variable 'check_dic' referenced before assignment
[2025-03-04 13:21:06,818] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:21:06: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:21:06,826] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP POST /MiscellaneousPurchases/Budget/ 500 [0.31, 127.0.0.1:63650]
[2025-03-04 13:21:55,482] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:21:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:21:55,499] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.11, 127.0.0.1:63737]
[2025-03-04 13:22:02,946] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:22:02: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:22:02,961] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.08, 127.0.0.1:63737]
[2025-03-04 13:22:23,209] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:22:23: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:22:23,223] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.06, 127.0.0.1:63737]
[2025-03-04 13:27:55,924] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:27:55: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:27:55,942] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.07, 127.0.0.1:64330]
[2025-03-04 13:27:56,166] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64330]
[2025-03-04 13:27:56,178] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:64331]
[2025-03-04 13:27:56,304] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:64333]
[2025-03-04 13:27:56,522] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:64331]
[2025-03-04 13:27:56,530] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64333]
[2025-03-04 13:27:56,577] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:64331]
[2025-03-04 13:27:56,929] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:27:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 13:27:56,947] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:64331]
[2025-03-04 13:27:56,979] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 13:27:56: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 13:27:57,007] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:64331]
[2025-03-04 14:03:01,630] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:03:01: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:03:01,648] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:51099]
[2025-03-04 14:03:01,655] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:64333]
[2025-03-04 14:03:01,746] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:51099]
[2025-03-04 14:03:01,768] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:51099]
[2025-03-04 14:03:01,819] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51102]
[2025-03-04 14:03:01,822] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51102]
[2025-03-04 14:03:01,934] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:51099]
[2025-03-04 14:03:01,943] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51099]
[2025-03-04 14:03:02,072] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:03:02: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:03:02,081] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:51099]
[2025-03-04 14:03:02,101] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:03:02: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:03:02,116] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:51100]
[2025-03-04 14:04:28,003] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:04:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:04:28,016] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:51531]
[2025-03-04 14:04:28,021] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51102]
[2025-03-04 14:04:28,093] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:51531]
[2025-03-04 14:04:28,104] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:51531]
[2025-03-04 14:04:28,160] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:51534]
[2025-03-04 14:04:28,162] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51534]
[2025-03-04 14:04:28,273] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:51531]
[2025-03-04 14:04:28,280] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:51532]
[2025-03-04 14:04:28,377] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:04:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:04:28,389] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:51532]
[2025-03-04 14:04:28,416] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:04:28: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:04:28,436] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:51531]
[2025-03-04 14:09:35,914] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:35: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:09:35,946] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:52108]
[2025-03-04 14:09:35,956] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:51534]
[2025-03-04 14:09:36,031] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:09:36,041] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:09:36,064] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52113]
[2025-03-04 14:09:36,067] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52113]
[2025-03-04 14:09:36,119] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:09:36,124] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52110]
[2025-03-04 14:09:36,268] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:36: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:09:36,283] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:52110]
[2025-03-04 14:09:36,298] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:36: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:09:36,326] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:52108]
[2025-03-04 14:09:39,675] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:09:39,706] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.08, 127.0.0.1:52108]
[2025-03-04 14:09:39,723] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52113]
[2025-03-04 14:09:39,801] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:09:39,809] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52110]
[2025-03-04 14:09:39,822] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52122]
[2025-03-04 14:09:39,843] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52122]
[2025-03-04 14:09:39,867] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:52110]
[2025-03-04 14:09:39,876] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:09:39,984] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:09:39,999] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.02, 127.0.0.1:52108]
[2025-03-04 14:09:40,016] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:09:40: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:09:40,041] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:52110]
[2025-03-04 14:10:16,050] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:16: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:10:16,077] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.06, 127.0.0.1:52110]
[2025-03-04 14:10:16,087] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52122]
[2025-03-04 14:10:16,153] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52110]
[2025-03-04 14:10:16,163] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:10:16,180] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52190]
[2025-03-04 14:10:16,183] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52190]
[2025-03-04 14:10:16,214] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:52108]
[2025-03-04 14:10:16,220] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:52110]
[2025-03-04 14:10:16,322] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:16: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:10:16,333] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:52110]
[2025-03-04 14:10:16,367] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:16: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:10:16,381] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:52108]
[2025-03-04 14:10:39,191] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:10:39,206] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:52108]
[2025-03-04 14:10:39,212] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52190]
[2025-03-04 14:10:39,271] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:10:39,282] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:52108]
[2025-03-04 14:10:39,291] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:52231]
[2025-03-04 14:10:39,294] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52231]
[2025-03-04 14:10:39,327] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.00, 127.0.0.1:52108]
[2025-03-04 14:10:39,333] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.00, 127.0.0.1:52110]
[2025-03-04 14:10:39,433] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:10:39,450] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:52110]
[2025-03-04 14:10:39,470] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:10:39: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:10:39,490] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:52108]
[2025-03-04 14:20:09,688] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:20:09: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:20:09,696] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:53045]
[2025-03-04 14:39:54,156] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:39:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:39:54,181] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.03, 127.0.0.1:54420]
[2025-03-04 14:39:54,191] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:52231]
[2025-03-04 14:39:54,270] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:54420]
[2025-03-04 14:39:54,297] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:54420]
[2025-03-04 14:39:54,353] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:54423]
[2025-03-04 14:39:54,356] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54423]
[2025-03-04 14:39:54,460] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:54420]
[2025-03-04 14:39:54,465] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:54421]
[2025-03-04 14:39:54,615] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:39:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 14:39:54,624] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:54421]
[2025-03-04 14:39:54,660] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:39:54: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:39:54,673] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:54420]
[2025-03-04 14:41:41,463] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:41: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 14:41:41,478] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.38, 127.0.0.1:54561]
[2025-03-04 14:41:41,722] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:41: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/'>
[2025-03-04 14:41:41,735] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.25, 127.0.0.1:54561]
[2025-03-04 14:41:41,782] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54423]
[2025-03-04 14:41:41,914] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:41: C1010S3/AnonymousUser/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:41:41,941] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.06, 127.0.0.1:54561]
[2025-03-04 14:41:45,333] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:45: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/login/?next=/admin/'>
[2025-03-04 14:41:45,352] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.88, 127.0.0.1:54561]
[2025-03-04 14:41:47,651] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:47: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 14:41:47,714] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [2.36, 127.0.0.1:54561]
[2025-03-04 14:41:48,002] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:41:47: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:41:48,047] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.10, 127.0.0.1:54561]
[2025-03-04 14:42:10,309] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/'>
[2025-03-04 14:42:10,328] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [2.61, 127.0.0.1:54561]
[2025-03-04 14:42:10,358] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:42:10,386] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [2.66, 127.0.0.1:54563]
[2025-03-04 14:42:10,416] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:10: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 14:42:10,433] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.08, 127.0.0.1:54561]
[2025-03-04 14:42:14,229] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:14: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/userinfo/'>
[2025-03-04 14:42:14,263] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/userinfo/ 200 [1.97, 127.0.0.1:54561]
[2025-03-04 14:42:14,288] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:14: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:42:14,311] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [2.01, 127.0.0.1:54563]
[2025-03-04 14:42:14,336] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:14: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 14:42:14,352] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.07, 127.0.0.1:54561]
[2025-03-04 14:42:15,154] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:15: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:42:15,182] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:54561]
[2025-03-04 14:42:43,794] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:42:43: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:42:43,822] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:54561]
[2025-03-04 14:43:09,211] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:09: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-04 14:43:09,235] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET / 200 [0.03, 127.0.0.1:54561]
[2025-03-04 14:43:09,378] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:54725]
[2025-03-04 14:43:09,383] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54725]
[2025-03-04 14:43:09,512] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:09: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/PermInfo/'>
[2025-03-04 14:43:09,528] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /PermInfo/ 200 [0.05, 127.0.0.1:54561]
[2025-03-04 14:43:09,572] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:09: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:43:09,592] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.07, 127.0.0.1:54563]
[2025-03-04 14:43:22,383] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:22: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:43:22,421] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.08, 127.0.0.1:54563]
[2025-03-04 14:43:22,454] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54725]
[2025-03-04 14:43:22,484] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:54862]
[2025-03-04 14:43:22,489] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54862]
[2025-03-04 14:43:22,619] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:22: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:43:22,637] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:54563]
[2025-03-04 14:43:22,680] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:22: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:43:22,706] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.13, 127.0.0.1:54561]
[2025-03-04 14:43:28,191] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:54561]
[2025-03-04 14:43:28,198] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:54563]
[2025-03-04 14:43:28,206] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:54872]
[2025-03-04 14:43:28,219] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:43:34,082] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:34: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:43:34,116] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.06, 127.0.0.1:54872]
[2025-03-04 14:43:34,127] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54862]
[2025-03-04 14:43:34,222] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:43:34,232] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:54563]
[2025-03-04 14:43:34,286] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:54886]
[2025-03-04 14:43:34,290] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54886]
[2025-03-04 14:43:34,364] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:54563]
[2025-03-04 14:43:34,409] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:54563]
[2025-03-04 14:43:34,502] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:34: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:43:34,521] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:54563]
[2025-03-04 14:43:34,569] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:34: C1010S3/edwin/Edwin> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:43:34,601] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.11, 127.0.0.1:54872]
[2025-03-04 14:43:56,278] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:56: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/logout/'>
[2025-03-04 14:43:56,282] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /logout/ 302 [0.02, 127.0.0.1:54872]
[2025-03-04 14:43:56,293] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:56: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 14:43:56,297] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:54872]
[2025-03-04 14:43:56,336] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54886]
[2025-03-04 14:43:56,407] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:43:56,424] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:56: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:43:56,426] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.01, 127.0.0.1:54872]
[2025-03-04 14:43:56,435] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:43:56: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 14:43:56,437] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:54872]
[2025-03-04 14:44:02,032] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:44:02: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/login/?next='>
[2025-03-04 14:44:02,049] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /login/?next= 302 [0.06, 127.0.0.1:54872]
[2025-03-04 14:44:02,061] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:44:02: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 14:44:02,083] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /login/ 302 [0.03, 127.0.0.1:54872]
[2025-03-04 14:44:02,111] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:44:02: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 14:44:02,128] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.04, 127.0.0.1:54872]
[2025-03-04 14:44:02,220] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:44:02,235] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:44:02,286] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:54955]
[2025-03-04 14:44:02,291] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54955]
[2025-03-04 14:44:02,326] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:44:02,386] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:54872]
[2025-03-04 14:44:02,665] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:44:02: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:44:02,758] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 14:44:02,770] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.14, 127.0.0.1:54872]
[2025-03-04 14:45:48,563] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:45:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/IssuesBreakdown/IssuesBreakdown_edit/'>
[2025-03-04 14:45:48,652] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /IssuesBreakdown/IssuesBreakdown_edit/ 200 [0.14, 127.0.0.1:55125]
[2025-03-04 14:45:49,100] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:55131]
[2025-03-04 14:45:49,105] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55131]
[2025-03-04 14:45:49,812] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:45:49: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/IssuesBreakdown/IssuesBreakdown_edit/'>
[2025-03-04 14:45:49,835] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /IssuesBreakdown/IssuesBreakdown_edit/ 200 [0.07, 127.0.0.1:55125]
[2025-03-04 14:45:49,860] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:45:49: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:45:49,907] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 14:45:49,912] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.11, 127.0.0.1:55126]
[2025-03-04 14:45:50,483] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55131]
[2025-03-04 14:46:36,964] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:46:36: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:46:36,998] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /SpecDownload/ManagementSop-summary/ 200 [0.07, 127.0.0.1:55126]
[2025-03-04 14:46:37,103] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:54955]
[2025-03-04 14:46:37,116] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:55126]
[2025-03-04 14:46:37,132] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:55126]
[2025-03-04 14:46:37,176] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:55218]
[2025-03-04 14:46:37,180] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55218]
[2025-03-04 14:46:37,252] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:55126]
[2025-03-04 14:46:37,306] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:55126]
[2025-03-04 14:46:37,405] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:46:37: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/SpecDownload/ManagementSop-summary/'>
[2025-03-04 14:46:37,421] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /SpecDownload/ManagementSop-summary/ 200 [0.04, 127.0.0.1:55126]
[2025-03-04 14:46:37,463] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 14:46:37: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 14:46:37,511] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 14:46:37,516] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.12, 127.0.0.1:55125]
[2025-03-04 16:04:10,794] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:10: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 16:04:10,814] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.04, 127.0.0.1:61512]
[2025-03-04 16:04:10,851] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:55218]
[2025-03-04 16:04:10,908] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:10,943] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:10,970] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61516]
[2025-03-04 16:04:10,973] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61516]
[2025-03-04 16:04:11,013] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:11,088] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:11,262] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:11: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:04:11,311] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:04:11,316] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.09, 127.0.0.1:61512]
[2025-03-04 16:04:13,684] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:13: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/SOPManager/'>
[2025-03-04 16:04:13,698] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/SOPManager/ 200 [0.04, 127.0.0.1:61512]
[2025-03-04 16:04:13,748] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:13: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations_Category/SOPManager/'>
[2025-03-04 16:04:13,763] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations_Category/SOPManager/ 200 [0.05, 127.0.0.1:61512]
[2025-03-04 16:04:13,841] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61516]
[2025-03-04 16:04:13,849] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:13,869] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:13,893] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61523]
[2025-03-04 16:04:13,896] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61523]
[2025-03-04 16:04:13,927] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:13,984] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:14,062] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:14: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/Navigations_Category/'>
[2025-03-04 16:04:14,075] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /Navigations_Category/ 200 [0.02, 127.0.0.1:61512]
[2025-03-04 16:04:14,090] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:14: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:04:14,138] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:04:14,141] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.08, 127.0.0.1:61513]
[2025-03-04 16:04:15,912] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:15: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 16:04:15,927] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.05, 127.0.0.1:61513]
[2025-03-04 16:04:16,003] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61513]
[2025-03-04 16:04:16,009] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61523]
[2025-03-04 16:04:16,012] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:16,022] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61530]
[2025-03-04 16:04:16,027] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61530]
[2025-03-04 16:04:16,069] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:16,080] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:16,138] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:16: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:04:16,188] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:04:16,194] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.07, 127.0.0.1:61512]
[2025-03-04 16:04:22,675] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:22: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/Budget/'>
[2025-03-04 16:04:22,695] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/Budget/ 200 [0.06, 127.0.0.1:61512]
[2025-03-04 16:04:22,738] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61530]
[2025-03-04 16:04:22,795] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:22,816] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:22,823] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61555]
[2025-03-04 16:04:22,827] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61555]
[2025-03-04 16:04:22,856] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61512]
[2025-03-04 16:04:22,865] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.02, 127.0.0.1:61513]
[2025-03-04 16:04:22,981] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:22: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 16:04:22,997] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:61513]
[2025-03-04 16:04:23,042] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:23: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:04:23,102] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:04:23,106] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.13, 127.0.0.1:61512]
[2025-03-04 16:04:27,508] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:04:27: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 16:04:27,542] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.05, 127.0.0.1:61512]
[2025-03-04 16:06:08,525] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:08: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:06:08,539] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.04, 127.0.0.1:61744]
[2025-03-04 16:06:08,624] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:61744]
[2025-03-04 16:06:08,635] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61555]
[2025-03-04 16:06:08,644] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:61744]
[2025-03-04 16:06:08,654] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61747]
[2025-03-04 16:06:08,657] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61747]
[2025-03-04 16:06:08,696] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61744]
[2025-03-04 16:06:08,703] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61745]
[2025-03-04 16:06:08,828] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:08: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/Budget/'>
[2025-03-04 16:06:08,840] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/Budget/ 200 [0.04, 127.0.0.1:61745]
[2025-03-04 16:06:08,859] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:08: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:06:08,918] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:06:08,923] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.11, 127.0.0.1:61744]
[2025-03-04 16:06:48,598] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:06:48,626] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.05, 127.0.0.1:61744]
[2025-03-04 16:06:48,636] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61747]
[2025-03-04 16:06:48,699] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.00, 127.0.0.1:61744]
[2025-03-04 16:06:48,709] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:61744]
[2025-03-04 16:06:48,727] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:61810]
[2025-03-04 16:06:48,730] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:61810]
[2025-03-04 16:06:48,762] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:61744]
[2025-03-04 16:06:48,768] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:61745]
[2025-03-04 16:06:48,864] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:06:48,877] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.03, 127.0.0.1:61745]
[2025-03-04 16:06:48,907] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:06:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:06:48,922] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:06:48,924] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.06, 127.0.0.1:61744]
[2025-03-04 16:11:39,379] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:11:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:11:39,393] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.10, 127.0.0.1:62237]
[2025-03-04 16:11:39,481] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:62237]
[2025-03-04 16:11:39,492] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.00, 127.0.0.1:62237]
[2025-03-04 16:11:39,537] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:62242]
[2025-03-04 16:11:39,643] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:62237]
[2025-03-04 16:11:39,651] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62242]
[2025-03-04 16:11:39,657] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.00, 127.0.0.1:62237]
[2025-03-04 16:11:39,830] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:11:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:11:39,844] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.06, 127.0.0.1:62237]
[2025-03-04 16:11:39,869] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:11:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:11:40,211] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:11:40,214] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.41, 127.0.0.1:62236]
[2025-03-04 16:14:48,402] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:14:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:14:48,425] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.05, 127.0.0.1:62489]
[2025-03-04 16:14:48,433] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62242]
[2025-03-04 16:14:48,525] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:62489]
[2025-03-04 16:14:48,545] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:62489]
[2025-03-04 16:14:48,603] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:62492]
[2025-03-04 16:14:48,607] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62492]
[2025-03-04 16:14:48,708] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:62489]
[2025-03-04 16:14:48,762] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:62489]
[2025-03-04 16:14:48,878] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:14:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:14:48,894] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.03, 127.0.0.1:62489]
[2025-03-04 16:14:48,927] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:14:48: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:14:48,947] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 80, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:14:48,949] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.07, 127.0.0.1:62490]
[2025-03-04 16:16:18,117] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:16:18: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:16:18,146] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.11, 127.0.0.1:62650]
[2025-03-04 16:16:18,218] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:62650]
[2025-03-04 16:16:18,231] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:62650]
[2025-03-04 16:16:18,241] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:62653]
[2025-03-04 16:16:18,323] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:62651]
[2025-03-04 16:16:18,329] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:62650]
[2025-03-04 16:16:18,331] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:62653]
[2025-03-04 16:16:18,398] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:16:18: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:16:18,411] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.04, 127.0.0.1:62650]
[2025-03-04 16:16:18,441] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:16:18: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:16:18,773] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:16:18,778] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.40, 127.0.0.1:62651]
[2025-03-04 16:17:39,536] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/permission/'>
[2025-03-04 16:17:39,551] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 302 [0.36, 127.0.0.1:62871]
[2025-03-04 16:17:39,595] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:17:39,657] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:17:39,665] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.41, 127.0.0.1:62873]
[2025-03-04 16:17:39,743] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/app01/permission/'>
[2025-03-04 16:17:39,758] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/app01/permission/ 200 [0.20, 127.0.0.1:62871]
[2025-03-04 16:17:39,881] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 16:17:39,894] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.04, 127.0.0.1:62871]
[2025-03-04 16:17:39,928] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:39: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/'>
[2025-03-04 16:17:39,941] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.04, 127.0.0.1:62871]
[2025-03-04 16:17:40,097] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:40: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:17:40,164] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:17:40,167] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.11, 127.0.0.1:62871]
[2025-03-04 16:17:43,176] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:43: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/login/?next=/admin/'>
[2025-03-04 16:17:43,207] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 200 [0.43, 127.0.0.1:62871]
[2025-03-04 16:17:43,290] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:43: C120W09/AnonymousUser/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:17:43,349] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:17:43,354] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.08, 127.0.0.1:62871]
[2025-03-04 16:17:45,745] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:45: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/login/?next=/admin/'>
[2025-03-04 16:17:45,760] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.40, 127.0.0.1:62871]
[2025-03-04 16:17:46,655] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 16:17:46,686] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [0.92, 127.0.0.1:62871]
[2025-03-04 16:17:46,882] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:17:47,127] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:17:47,132] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.30, 127.0.0.1:62871]
[2025-03-04 16:17:52,290] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:52: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/permission/'>
[2025-03-04 16:17:52,308] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/permission/ 200 [1.19, 127.0.0.1:62871]
[2025-03-04 16:17:52,344] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:52: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:17:52,394] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:17:52,398] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [1.26, 127.0.0.1:62873]
[2025-03-04 16:17:52,412] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:17:52: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:17:52,427] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.09, 127.0.0.1:62871]
[2025-03-04 16:18:07,917] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:07: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/userinfo/'>
[2025-03-04 16:18:07,952] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/userinfo/ 200 [2.03, 127.0.0.1:62871]
[2025-03-04 16:18:07,979] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:07: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:18:08,033] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:18:08,038] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [2.10, 127.0.0.1:62873]
[2025-03-04 16:18:09,953] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:09: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/'>
[2025-03-04 16:18:09,974] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [3.15, 127.0.0.1:62932]
[2025-03-04 16:18:09,992] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:09: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:18:10,007] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [2.03, 127.0.0.1:62871]
[2025-03-04 16:18:10,043] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:10: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:18:10,094] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:18:10,097] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [2.05, 127.0.0.1:62873]
[2025-03-04 16:18:10,125] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:10: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:18:10,142] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.13, 127.0.0.1:62932]
[2025-03-04 16:18:24,168] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:24: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:18:24,239] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:18:24,244] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.12, 127.0.0.1:62932]
[2025-03-04 16:18:25,574] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:25: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/menu/'>
[2025-03-04 16:18:25,590] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/menu/ 200 [0.41, 127.0.0.1:62932]
[2025-03-04 16:18:25,615] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:25: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:18:25,674] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:18:25,679] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.49, 127.0.0.1:62873]
[2025-03-04 16:18:25,693] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:18:25: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:18:25,713] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.10, 127.0.0.1:62932]
[2025-03-04 16:31:13,055] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:31:13: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-04 16:31:13,317] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:31:13,321] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET / 500 [0.36, 127.0.0.1:63986]
[2025-03-04 16:31:13,444] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:31:13: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:31:13,474] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:31:13,476] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.06, 127.0.0.1:63986]
[2025-03-04 16:34:10,529] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:34:10: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/'>
[2025-03-04 16:34:10,825] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:38:32,548] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:38:32: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:38:32,814] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 14, in __call__
    response = self.process_request(request)
  File "C:\djangoproject\Reliability_Row_data\middleware\checkper.py", line 81, in process_request
    info = '<br/>' + ('<br/>'.join(permission_url))
TypeError: sequence item 133: expected str instance, NoneType found
[2025-03-04 16:38:32,817] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /favicon.ico 500 [0.35, 127.0.0.1:64559]
[2025-03-04 16:41:47,299] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:47: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/logout/'>
[2025-03-04 16:41:47,304] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /logout/ 302 [0.30, 127.0.0.1:64836]
[2025-03-04 16:41:47,355] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:47: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:41:47,359] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.05, 127.0.0.1:64836]
[2025-03-04 16:41:47,473] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:64836]
[2025-03-04 16:41:47,487] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:47: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:41:47,492] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.01, 127.0.0.1:64836]
[2025-03-04 16:41:47,500] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:47: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:41:47,503] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:64836]
[2025-03-04 16:41:57,644] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:57: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:41:57,646] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.01, 127.0.0.1:64836]
[2025-03-04 16:41:57,655] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:41:57: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:41:57,659] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:64836]
[2025-03-04 16:42:05,123] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/userinfo/23/change/'>
[2025-03-04 16:42:05,127] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/app01/userinfo/23/change/ 302 [0.23, 127.0.0.1:64836]
[2025-03-04 16:42:05,194] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/app01/userinfo/23/change/'>
[2025-03-04 16:42:05,198] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/app01/userinfo/23/change/ 200 [0.07, 127.0.0.1:64836]
[2025-03-04 16:42:05,316] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 16:42:05,318] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /admin/ 302 [0.00, 127.0.0.1:64836]
[2025-03-04 16:42:05,339] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/login/?next=/admin/'>
[2025-03-04 16:42:05,342] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/login/?next=/admin/ 200 [0.02, 127.0.0.1:64836]
[2025-03-04 16:42:05,459] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:42:05,461] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.01, 127.0.0.1:64836]
[2025-03-04 16:42:05,468] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:05: None/AnonymousUser/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:42:05,470] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.01, 127.0.0.1:64836]
[2025-03-04 16:42:07,696] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:07: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/login/?next=/admin/'>
[2025-03-04 16:42:07,707] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/login/?next=/admin/ 302 [0.37, 127.0.0.1:64836]
[2025-03-04 16:42:09,697] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:09: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/'>
[2025-03-04 16:42:09,742] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/ 200 [2.03, 127.0.0.1:64836]
[2025-03-04 16:42:09,956] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:09: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:42:09,980] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [0.07, 127.0.0.1:64836]
[2025-03-04 16:42:10,019] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:10: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:42:10,037] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.05, 127.0.0.1:64836]
[2025-03-04 16:42:15,495] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:15: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/'>
[2025-03-04 16:42:15,518] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [2.12, 127.0.0.1:64836]
[2025-03-04 16:42:15,558] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:15: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:42:15,574] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [2.16, 127.0.0.1:64838]
[2025-03-04 16:42:15,592] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:15: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:42:15,608] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:64836]
[2025-03-04 16:42:15,639] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:15: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:42:15,654] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.07, 127.0.0.1:64838]
[2025-03-04 16:42:20,693] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:20: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/17/change/'>
[2025-03-04 16:42:20,713] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/17/change/ 200 [0.97, 127.0.0.1:64838]
[2025-03-04 16:42:20,782] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:42:20: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:42:20,795] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:64838]
[2025-03-04 16:43:21,742] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:21: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/app01/role/17/change/'>
[2025-03-04 16:43:21,755] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/app01/role/17/change/ 302 [0.06, 127.0.0.1:65001]
[2025-03-04 16:43:24,168] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:24: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/'>
[2025-03-04 16:43:24,240] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:24: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/admin/app01/role/17/change/'>
[2025-03-04 16:43:24,259] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /admin/app01/role/17/change/ 302 [0.52, 127.0.0.1:65008]
[2025-03-04 16:43:26,590] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:26: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/role/'>
[2025-03-04 16:43:26,622] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/role/ 200 [2.36, 127.0.0.1:65008]
[2025-03-04 16:43:26,692] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:26: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:43:26,704] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:65008]
[2025-03-04 16:43:32,290] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:32: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/app01/userinfo/'>
[2025-03-04 16:43:32,309] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/app01/userinfo/ 200 [2.20, 127.0.0.1:65008]
[2025-03-04 16:43:32,342] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:32: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:43:32,355] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 302 [2.23, 127.0.0.1:65018]
[2025-03-04 16:43:32,369] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:32: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/admin/jsi18n/'>
[2025-03-04 16:43:32,387] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /admin/jsi18n/ 200 [0.05, 127.0.0.1:65008]
[2025-03-04 16:43:32,426] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:32: None/edwin/None> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:43:32,437] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /login/ 200 [0.08, 127.0.0.1:65018]
[2025-03-04 16:43:46,265] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/login/?next='>
[2025-03-04 16:43:46,288] [runserver.py:147] [runserver:log_action] [INFO]- HTTP POST /login/?next= 302 [0.07, 127.0.0.1:65018]
[2025-03-04 16:43:46,323] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/login/'>
[2025-03-04 16:43:46,341] [runserver.py:147] [runserver:log_action] [INFO]- HTTP GET /login/ 302 [0.05, 127.0.0.1:65018]
[2025-03-04 16:43:46,399] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/Navigations/'>
[2025-03-04 16:43:46,417] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /Navigations/ 200 [0.07, 127.0.0.1:65018]
[2025-03-04 16:43:46,538] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:65018]
[2025-03-04 16:43:46,547] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:65008]
[2025-03-04 16:43:46,590] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:65045]
[2025-03-04 16:43:46,748] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:65018]
[2025-03-04 16:43:46,758] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.02, 127.0.0.1:65008]
[2025-03-04 16:43:46,762] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65045]
[2025-03-04 16:43:46,879] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:46: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:43:46,910] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.05, 127.0.0.1:65008]
[2025-03-04 16:43:56,824] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:56: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:43:56,851] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /MiscellaneousPurchases/ReceiptAmount/ 200 [0.05, 127.0.0.1:65008]
[2025-03-04 16:43:56,908] [runserver.py:160] [runserver:log_action] [INFO]- WebSocket DISCONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65045]
[2025-03-04 16:43:56,972] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/css/bootstrap.min.css.map 404 [0.01, 127.0.0.1:65008]
[2025-03-04 16:43:56,982] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/lib/bootstrap.min.js.map 404 [0.01, 127.0.0.1:65008]
[2025-03-04 16:43:57,021] [runserver.py:162] [runserver:log_action] [INFO]- WebSocket HANDSHAKING /ws/msg/Reliability_Row_data/ [127.0.0.1:65087]
[2025-03-04 16:43:57,024] [runserver.py:158] [runserver:log_action] [INFO]- WebSocket CONNECT /ws/msg/Reliability_Row_data/ [127.0.0.1:65087]
[2025-03-04 16:43:57,121] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/axios.min.map 404 [0.01, 127.0.0.1:65008]
[2025-03-04 16:43:57,130] [runserver.py:149] [runserver:log_action] [WARNING]- HTTP GET /static/js/xlsx/FileSaver.min.js.map 404 [0.01, 127.0.0.1:65018]
[2025-03-04 16:43:57,252] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:57: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: POST '/MiscellaneousPurchases/ReceiptAmount/'>
[2025-03-04 16:43:57,270] [runserver.py:141] [runserver:log_action] [INFO]- HTTP POST /MiscellaneousPurchases/ReceiptAmount/ 200 [0.04, 127.0.0.1:65018]
[2025-03-04 16:43:57,294] [UserIP.py:93] [UserIP:process_response] [INFO]- 2025-03-04 16:43:57: C120W09/edwin/Cao. Katherine> None/None/None > 127.0.0.1/127.0.0.1 > <AsgiRequest: GET '/favicon.ico'>
[2025-03-04 16:43:57,327] [runserver.py:141] [runserver:log_action] [INFO]- HTTP GET /favicon.ico 200 [0.08, 127.0.0.1:65008]
