[2024-09-13 07:44:00,724] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /admin/CriticalIssueCrossCheck/criticalissue/add/
Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 163, in __getitem__
    field = self.fields[name]
KeyError: 'IssueNum'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python372\mecheck\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python372\mecheck\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python372\mecheck\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python372\mecheck\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python372\mecheck\lib\site-packages\django\template\defaulttags.py", line 165, in render
    values = list(values)
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 118, in __iter__
    yield AdminField(self.form, field, is_first=(i == 0))
  File "C:\Python372\mecheck\lib\site-packages\django\contrib\admin\helpers.py", line 130, in __init__
    self.field = form[field]  # A django.forms.BoundField instance
  File "C:\Python372\mecheck\lib\site-packages\django\forms\forms.py", line 169, in __getitem__
    ', '.join(sorted(f for f in self.fields)),
KeyError: "Key 'IssueNum' not found in 'CriticalIssueForm'. Choices are: Action, CG, Category, Object, Photo, Project, Reproduce_Steps, Root_Cause, Solution, Status, Symptom, edit_time, editor, video."
[2024-09-13 07:44:00,743] [runserver.py:154] [runserver:log_action] [ERROR]- HTTP GET /admin/CriticalIssueCrossCheck/criticalissue/add/ 500 [0.15, 127.0.0.1:65021]
